-- +migrate Up
ALTER TABLE "model" ADD COLUMN "model_type" INT NOT NULL DEFAULT 0;
ALTER TABLE "model" ADD COLUMN "c" DOUBLE PRECISION DEFAULT 0.0 NOT NULL;
ALTER TABLE "model" ADD COLUMN "accuracy" DOUBLE PRECISION DEFAULT 0.0 NOT NULL;
ALTER TABLE "