name: build and test
on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: nobody 
          POSTGRES_PASSWORD: nobody 
          POSTGRES_DB: go-active-learning-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres
    steps:
      - name: checkout
        us